const MONGODB_PRODUCTS_COLLECTION =
  process.env.MONGODB_PRODUCTS_COLLECTION ?? "documents";

const MONGODB_FAVORITES_COLLECTION =
  process.env.MONGODB_FAVORITES_COLLECTION ?? "favorites";

const MONGODB_ATLAS_SEARCH_INDEX =
  process.env.MONGODB_ATLAS_SEARCH_INDEX ?? "default";

export {
  MONGODB_PRODUCTS_COLLECTION,
  MONGODB_FAVORITES_COLLECTION,
  MONGODB_ATLAS_SEARCH_INDEX,
};

